//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reseñaModeloPrjct.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class modeloBDContainer : DbContext
    {
        public modeloBDContainer()
            : base("name=modeloBDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Reseña> Reseña { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<Comentario> ComentarioSet { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
    }
}
