//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reseñaModeloPrjct.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reseña
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reseña()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int IdReseña { get; set; }
        public string titulo_reseña { get; set; }
        public string contenido_reseña { get; set; }
        public Nullable<decimal> puntuacion_reseña { get; set; }
        public System.DateTime fecha_reseña { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
